# file: docker-compose.yaml
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "svadmin"
      POSTGRES_PASSWORD: "Qwerty123"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U svadmin" ]
      interval: 10s
      timeout: 10s
      retries: 5
  marketplace_app:
    build: .
    image: "marketplace_app"
    ports:
      - "8080:8080"
    links:
      - "postgres"
    depends_on:
      - "postgres"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: svadmin
      SPRING_DATASOURCE_PASSWORD: Qwerty123