# file: docker-compose.yaml
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "svadmin"
      POSTGRES_PASSWORD: "Qwerty123"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U psgadmin" ]
      interval: 10s
      timeout: 10s
      retries: 5